# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: bbyunis
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: lymeid # "service" is the name of this project. This will also be added to your AWS resource names.
service: landing-sdk-api

provider:
  name: aws
  runtime: python3.11
  ecr:
    images:
      segmentationimage:
        path: ./
        file: Dockerfile-segmentation
      classificationimage:
        path: ./
        file: Dockerfile-classification
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
      - 'application/json'
      - 'application/octet-stream'

functions:
  segmentation:
    image:
      name: segmentationimage
    timeout: 30
    events:
      - http:
          path: /segmentation
          method: post
  classification:
    image:
      name: classificationimage
    timeout: 30
    events:
      - http:
          path: /classification
          method: post

plugins:
  - serverless-offline
